#!/bin/bash

echo "🔧 Setting up Supabase database tables..."
echo ""
echo "Please follow these steps:"
echo "1. Go to https://supabase.com/dashboard"
echo "2. Open your project: qzuddqptlgcqfwbjjarl"
echo "3. Navigate to the SQL Editor"
echo "4. Click 'New Query'"
echo "5. Copy and paste the contents of: supabase-schema.sql"
echo "6. Click 'Run'"
echo ""
echo "Alternatively, you can use the CLI:"
echo "  supabase db push"
echo ""
echo "The friendships table schema:"
echo "  CREATE TABLE public.friendships ("
echo "    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),"
echo "    from_user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,"
echo "    to_user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,"
echo "    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED')),"
echo "    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),"
echo "    UNIQUE(from_user_id, to_user_id)"
echo "  );"
echo ""
echo "Once the tables are created, reload the app (Press r in the Metro bundler)"
